# seo/content
title: Shoes
description: Shoes is a tiny GUI toolkit for writing fun, simple applications in Ruby.
keywords: ruby, gui, simple, ease, fun, native applications, toolkit, gui toolkit, windows, mac, Linux, cross platform, app, beginner, packaging

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-mentions

# meta
highlighter: pygments
permalink: pretty

# assets
sass:
  style: :compressed
  sass_dir: /css/
